# 数据源配置
spring:
  datasource:
    driver:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.188.90.126:13306/bz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: bz
    password: ZHzxR3HKs76C8Dy2
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

logging:
  level:
    com.tzs: debug
    root: debug
  file:
    path: src\main\resources\logger\ # logger文件夹需要提前生成