adminHost: 127.0.0.1
server:
  port: 8088
#  1.7
#  servlet-path: /tzs
#  1.8
  servlet:
    context-path: /tzs
  session:
    timeout: 1800
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: tzs
  profiles:
    active: dev
  thymeleaf:
    #缓冲的配置
    cache: true
    check-template: true
    check-template-location: true
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis配置
mybatis:
  type-aliases-package: com.bz.entity
  mapper-locations: classpath:/mappers/*
  configuration:
    map-underscore-to-camel-case: true

upload:
  # 配置服务器域名
  domain:
  address: /other/upload/

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: tzsbz #JWT加解密使用的密钥
  expiration: 1800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头

